# See values.yaml for how $shouldInstallFunctionNamespace's value is determined
{{- $shouldInstallFunctionNamespace := (ne (.Values.createFunctionNamespace | typeOf) "<nil>") | ternary .Values.createFunctionNamespace .Release.IsInstall -}}
{{- if $shouldInstallFunctionNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "openfaas.functionNamespace" . | quote }}
  labels:
    istio-injection: enabled
    role: openfaas-fn
{{- end }}